package requests

type OperationComponent struct {
	MaenanceOrder                  string  `json:"MaenanceOrder"`
	MaenanceOrderComponent         string  `json:"MaenanceOrderComponent"`
	Reservation                    *string `json:"Reservation"`
	ReservationItem                *string `json:"ReservationItem"`
	ReservationType                *string `json:"ReservationType"`
	MaOrderRoutingNumber           *string `json:"MaOrderRoutingNumber"`
	MaOrderOperationCounter        *string `json:"MaOrderOperationCounter"`
	Product                        *string `json:"Product"`
	MaOrdOperationComponentText    *string `json:"MaOrdOperationComponentText"`
	MaOrdOpCompRequiredQuantity    *string `json:"MaOrdOpCompRequiredQuantity"`
	BaseUnit                       *string `json:"BaseUnit"`
	QuantityInUnitOfEntry          *string `json:"QuantityInUnitOfEntry"`
	UnitOfEntry                    *string `json:"UnitOfEntry"`
	RequirementDate                *string `json:"RequirementDate"`
	RequirementTime                *string `json:"RequirementTime"`
	Supplier                       *string `json:"Supplier"`
	Plant                          *string `json:"Plant"`
	StorageLocation                *string `json:"StorageLocation"`
	MaOrdOpCompItemCategory        *string `json:"MaOrdOpCompItemCategory"`
	GoodsMovementType              *string `json:"GoodsMovementType"`
	ReservationIsFinallyIssued     *int    `json:"ReservationIsFinallyIssued"`
	ProductGroup                   *string `json:"ProductGroup"`
	ProductTypeCode                *string `json:"ProductTypeCode"`
	ServicePerformer               *string `json:"ServicePerformer"`
	PerformancePeriodStartDateTime *string `json:"PerformancePeriodStartDateTime"`
	PerformancePeriodStartDate     *string `json:"PerformancePeriodStartDate"`
	PerformancePeriodEndDate       *string `json:"PerformancePeriodEndDate"`
	PerformancePeriodEndDateTime   *string `json:"PerformancePeriodEndDateTime"`
	PerformancePeriodStartTime     *string `json:"PerformancePeriodStartTime"`
	PerformancePeriodEndTime       *string `json:"PerformancePeriodEndTime"`
	LeanServiceDuration            *string `json:"LeanServiceDuration"`
	LeanServiceDurationUnit        *string `json:"LeanServiceDurationUnit"`
	DistributionFunction           *string `json:"DistributionFunction"`
	SrvcSchedgIsAlignedWthOpWrkCtr *string `json:"SrvcSchedgIsAlignedWthOpWrkCtr"`
	MaOrderCompDebitCreditCode     *string `json:"MaOrderCompDebitCreditCode"`
	GoodsMovementIsAllowed         *int    `json:"GoodsMovementIsAllowed"`
	MaenanceOrderComponentBatch    *string `json:"MaenanceOrderComponentBatch"`
	QuantityIsFixed                *int    `json:"QuantityIsFixed"`
	MaOrdOpComponentGLAccount      *string `json:"MaOrdOpComponentGLAccount"`
	MaOrdOpCompCostingRelevancy    *string `json:"MaOrdOpCompCostingRelevancy"`
	MaCompAltvProdUsgeRateInPct    *string `json:"MaCompAltvProdUsgeRateInPct"`
	MaOrderOpComponentSortText     *string `json:"MaOrderOpComponentSortText"`
	MaOrdOpCompIsBulkProduct       *int    `json:"MaOrdOpCompIsBulkProduct"`
	MaterialProvisionType          *string `json:"MaterialProvisionType"`
	MaOrdOpCompAssgdWBSElmnt       *string `json:"MaOrdOpCompAssgdWBSElmnt"`
	MaOrderOpComponentPrice        *string `json:"MaOrderOpComponentPrice"`
	MaOrdOpComponentCurrency       *string `json:"MaOrdOpComponentCurrency"`
	MatlCompIsMarkedForBackflush   *int    `json:"MatlCompIsMarkedForBackflush"`
	PurchasingGroup                *string `json:"PurchasingGroup"`
	DeliveryTimeInDays             *string `json:"DeliveryTimeInDays"`
	MaOrdOpCompGdsRecipientName    *string `json:"MaOrdOpCompGdsRecipientName"`
	MaOrdOpCompUnloadingPtTxt      *string `json:"MaOrdOpCompUnloadingPtTxt"`
	GoodsReceiptDurationInWorkDays *string `json:"GoodsReceiptDurationInWorkDays"`
	PurchasingInfoRecord           *string `json:"PurchasingInfoRecord"`
	OperationLeadTimeOffset        *string `json:"OperationLeadTimeOffset"`
	OpsLeadTimeOffsetUnit          *string `json:"OpsLeadTimeOffsetUnit"`
	MaOrdOpCompRequisitioner       *string `json:"MaOrdOpCompRequisitioner"`
	MaOrdOpCompProcmtTrckgNmbr     *string `json:"MaOrdOpCompProcmtTrckgNmbr"`
	ResponsiblePurchaseOrg         *string `json:"ResponsiblePurchaseOrg"`
	MaOrdOpCompSpecialStockType    *string `json:"MaOrdOpCompSpecialStockType"`
	VariableSizeDimension1         *string `json:"VariableSizeDimension1"`
	VariableSizeDimensionUnit      *string `json:"VariableSizeDimensionUnit"`
	VariableSizeCompFormulaKey     *string `json:"VariableSizeCompFormulaKey"`
	VariableSizeDimension2         *string `json:"VariableSizeDimension2"`
	NumberOfVariableSizeItem       *int    `json:"NumberOfVariableSizeItem"`
	VariableSizeDimension3         *string `json:"VariableSizeDimension3"`
	VariableSizeItemQuantity       *string `json:"VariableSizeItemQuantity"`
	VariableSizeComponentUnit      *string `json:"VariableSizeComponentUnit"`
	RqmtDateIsEnteredManually      *int    `json:"RqmtDateIsEnteredManually"`
	SupplierProduct                *string `json:"SupplierProduct"`
	MaOrdCompPurOutlineAgrmtItm    *string `json:"MaOrdCompPurOutlineAgrmtItm"`
	MaOrderComponenternalID        *string `json:"MaOrderComponenternalID"`
	PurchaseRequisition            *string `json:"PurchaseRequisition"`
	PurchaseRequisitionItem        *string `json:"PurchaseRequisitionItem"`
	OverallLimitAmount             *string `json:"OverallLimitAmount"`
	ExpectedOverallLimitAmount     *string `json:"ExpectedOverallLimitAmount"`
}
